//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prints.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prints.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Printgur - Auth Server&lt;/title&gt;
        ///    &lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; href=&quot;https://i.imgur.com/YnNAXtk.png&quot; /&gt;
        ///    &lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.googleapis.com&quot;&gt;
        ///    &lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.gstatic.com&quot; crossorigin&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;style&gt;
        ///        * {
        ///            font-family: &apos;Roboto&apos;, sans-serif;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string auth {
            get {
                return ResourceManager.GetString("auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- IMGUR API sends a invalid query string which I couldn&apos;t fix with C# so this page fixes the URL and redirects to the real
        ///auth endpoint --&gt;
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Printgur - Auth Server&lt;/title&gt;
        ///    &lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; href=&quot;https://i.imgur.com/YnNAXtk.png&quot; /&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;h1&gt;Redirecting...&lt;/h1&gt;
        ///
        ///    &lt;script&gt;
        ///        let url = window.location.href;
        ///
        ///        if (url.includes(&apos;state=#&apos;)) {
        ///            url = url.replace(&apos;state=#&apos;, &apos;&apos;);
        ///        } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string auth_fix {
            get {
                return ResourceManager.GetString("auth_fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printgur_black {
            get {
                object obj = ResourceManager.GetObject("printgur_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printgur_white {
            get {
                object obj = ResourceManager.GetObject("printgur_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
